pyspark:
  build: .
  dockerfile: ./Dockerfile
  hostname: pyspark
  ports:
    - "8888:8888"
  volumes:
    - ./notebooks:/spark/notebooks
  environment:
    IPYTHON_OPTS: notebook --ip='*' --no-browser
